/* SCRIPT PARA POBLAR LAS TABLAS */

/* POBLAMOS LA TABLA TYPE*/
INSERT INTO Type
VALUES (DEFAULT, "Comprador");

INSERT INTO Type
VALUES (DEFAULT, "Vendedor");

/* POBLAMOS LA TABLA COLORS*/
INSERT INTO Colors
VALUES (DEFAULT, "Rojo");

INSERT INTO Colors
VALUES (DEFAULT, "Naranja");

INSERT INTO Colors
VALUES (DEFAULT, "Amarillo");

INSERT INTO Colors
VALUES (DEFAULT, "Verde");

INSERT INTO Colors
VALUES (DEFAULT, "Celeste");

INSERT INTO Colors
VALUES (DEFAULT, "Azul");

INSERT INTO Colors
VALUES (DEFAULT, "Violeta");

INSERT INTO Colors
VALUES (DEFAULT, "Rosa");

INSERT INTO Colors
VALUES (DEFAULT, "Blanco");

INSERT INTO Colors
VALUES (DEFAULT, "Negro");

/* POBLAMOS LA TABLA SIZES*/
INSERT INTO Sizes
VALUES (DEFAULT, "S");

INSERT INTO Sizes
VALUES (DEFAULT, "M");

INSERT INTO Sizes
VALUES (DEFAULT, "L");

INSERT INTO Sizes
VALUES (DEFAULT, "XL");

INSERT INTO Sizes
VALUES (DEFAULT, "XXL");

/* POBLAMOS LA TABLA CATEGORIES*/
INSERT INTO Categories
VALUES (DEFAULT, "Hombre");

INSERT INTO Categories
VALUES (DEFAULT, "Mujer");

INSERT INTO Categories
VALUES (DEFAULT, "Unisex");

/* POBLAMOS LA TABLA SUBCATEGORIES*/
INSERT INTO subCategories
VALUES (DEFAULT, "Remera");

INSERT INTO subCategories
VALUES (DEFAULT, "Pantalon");

INSERT INTO subCategories
VALUES (DEFAULT, "Camisa");

INSERT INTO subCategories
VALUES (DEFAULT, "Campera");