-- MySQL Script generated by MySQL Workbench
-- COPIAR Y PEGAR EL CONTENIDO DEL SCRIPT EN WORKBECNH 


-- Thu Jan  5 17:26:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema structure
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema structure
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `structure` DEFAULT CHARACTER SET utf8mb4 ;
USE `structure` ;

-- -----------------------------------------------------
-- Table `structure`.`subCategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `structure`.`subCategories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `structure`.`Colors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `structure`.`Colors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `structure`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `structure`.`Categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `genre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `structure`.`Sizes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `structure`.`Sizes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `structure`.`Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `structure`.`Type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `structure`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `structure`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(45) NULL,
  `typeId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_Type1_idx` (`typeId` ASC)  ,
  CONSTRAINT `fk_users_Type1`
    FOREIGN KEY (`typeId`)
    REFERENCES `structure`.`Type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `structure`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `structure`.`Products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT(200) NOT NULL,
  `description` VARCHAR(256) NOT NULL,
  `condition` VARCHAR(45) NOT NULL,
  `brand` VARCHAR(45) NULL,
  `price` VARCHAR(45) NOT NULL,
  `image` VARCHAR(200) NOT NULL,
  `subCategoriesId` INT NOT NULL,
  `colorsId` INT NOT NULL,
  `categoriesId` INT NOT NULL,
  `sizesId` INT NOT NULL,
  `sellerId`INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Products_subCategories1_idx` (`subCategoriesId` ASC)  ,
  INDEX `fk_Products_Colors1_idx` (`colorsId` ASC)  ,
  INDEX `fk_Products_Categories1_idx` (`categoriesId` ASC)  ,
  INDEX `fk_Products_Sizes1_idx` (`sizesId` ASC)  ,
  INDEX `fk_Users_idx` (`sellerId` ASC)  ,
  CONSTRAINT `fk_Products_subCategories1`
    FOREIGN KEY (`subCategoriesId`)
    REFERENCES `structure`.`subCategories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_Colors1`
    FOREIGN KEY (`colorsId`)
    REFERENCES `structure`.`Colors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_Categories1`
    FOREIGN KEY (`categoriesId`)
    REFERENCES `structure`.`Categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_Sizes1`
    FOREIGN KEY (`sizesId`)
    REFERENCES `structure`.`Sizes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_idx`
    FOREIGN KEY (`sellerId`)
    REFERENCES `structure`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `structure`.`Carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `structure`.`Carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `totalPrice` FLOAT NOT NULL,
  `totalAmount` FLOAT NOT NULL,
  `usersId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Carts_users1_idx` (`usersId` ASC)  ,
  CONSTRAINT `fk_Carts_users1`
    FOREIGN KEY (`usersId`)
    REFERENCES `structure`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `structure`.`CartsProducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `structure`.`CartsProducts` (
  `idCart` INT NOT NULL,
  `idProduct` INT NOT NULL,
  `amount` FLOAT NOT NULL,
  `cartsId` INT NOT NULL,
  PRIMARY KEY (`idCart`),
  INDEX `fk_Carts_has_Products_Products1_idx` (`idProduct` ASC)  ,
  INDEX `fk_CartsProducts_Carts1_idx` (`cartsId` ASC)  ,
  CONSTRAINT `fk_Carts_has_Products_Products1`
    FOREIGN KEY (`idProduct`)
    REFERENCES `structure`.`Products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CartsProducts_Carts1`
    FOREIGN KEY (`cartsId`)
    REFERENCES `structure`.`Carts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;